name: .deb -> S3

on:
  push:
    branches: main
    paths:
      - 'stage/**'
      - '.github/**'
  repository_dispatch:
  workflow_dispatch:

concurrency:
  group: debian_builder
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.host-os }}
    strategy:
      matrix:
        stage: [unstable, testing, release]
        distro-codename: [ubuntu-focal-amd64, ubuntu-focal-arm64, ubuntu-jammy-amd64, ubuntu-jammy-arm64, debian-bullseye-amd64, debian-bullseye-arm64]
        include:
          - distro-codename: ubuntu-focal-amd64
            host-os: ubuntu-20.04
            arch: amd64
            distro: ubuntu
            codename: focal
          - distro-codename: ubuntu-focal-arm64
            host-os: [self-hosted, Linux, arm64, focal]
            arch: arm64
            distro: ubuntu
            codename: focal
          - distro-codename: ubuntu-jammy-amd64
            host-os: [self-hosted, Linux, X64, jammy]
            arch: amd64
            distro: ubuntu
            codename: jammy
          - distro-codename: ubuntu-jammy-arm64
            host-os: [self-hosted, Linux, arm64, jammy]
            arch: arm64
            distro: ubuntu
            codename: jammy
          - distro-codename: debian-bullseye-amd64
            host-os: ubuntu-20.04
            arch: amd64
            distro: debian
            codename: bullseye
          - distro-codename: debian-bullseye-arm64
            host-os: [self-hosted, Linux, arm64, focal]
            arch: arm64
            distro: debian
            codename: bullseye
    steps:
      - uses: actions/checkout@v2
      - name: Set Job Parameters
        id: init
        run: |
          echo ::set-output name=MANIFEST_PATH::"${{ github.workspace }}/manifests"
          echo ::set-output name=PKG_REPO_PATH::"${{ github.workspace }}/repo"
          echo ::set-output name=PKG_BUILD_DIR::"${{ github.workspace }}/packages"
          echo ::set-output name=GH_REPO_ROOT::"${{ github.workspace }}"
          echo ::set-output name=stage::${{ matrix.stage }}
          echo ::set-output name=distro::${{ matrix.distro }}
          echo ::set-output name=codename::${{ matrix.codename }}
          echo ::set-output name=arch::${{ matrix.arch }}
          echo ::set-output name=target::${{ matrix.stage }}-${{ matrix.distro }}-${{ matrix.codename }}-${{ matrix.arch }}
          echo ::set-output name=s3_bucket::regolith-${{ matrix.stage }}-${{ matrix.distro }}-${{ matrix.codename }}-${{ matrix.arch }}
          echo ::set-output name=repo_url::https://regolith-${{ matrix.stage }}-${{ matrix.distro }}-${{ matrix.codename }}-${{ matrix.arch }}.s3.us-east-2.amazonaws.com
      - name: Env setup
        run: |
          set -x
          set -e
          rm -Rf ${{ steps.init.outputs.PKG_REPO_PATH }} || true
          rm -Rf ${{ steps.init.outputs.MANIFEST_PATH }} || true
          mkdir ${{ steps.init.outputs.MANIFEST_PATH }}
          rm -Rf ${{ steps.init.outputs.PKG_BUILD_DIR }} || true
          mkdir ${{ steps.init.outputs.PKG_BUILD_DIR }}
          sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install -y --no-install-recommends jq git devscripts reprepro wget
      - name: Pull Manifest
        run: |
          set -x
          set -e
          manifest_url="https://${{ steps.init.outputs.s3_bucket }}.s3.us-east-2.amazonaws.com/manifest.txt"
          wget -P "${{ steps.init.outputs.PKG_REPO_PATH }}" "$manifest_url" || true
      - name: Check for changes
        id: changes
        run: |
          set -x
          set -e
          CHANGE_OUTPUT=$(${{ steps.init.outputs.GH_REPO_ROOT }}/.github/scripts/main.sh ${{ steps.init.outputs.GH_REPO_ROOT }} ${{ steps.init.outputs.GH_REPO_ROOT }}/.github/scripts/ext-debian.sh "${{ steps.init.outputs.stage }}" "${{ steps.init.outputs.distro }}" "${{ steps.init.outputs.codename }}" "${{ steps.init.outputs.arch }}" "unneeded to check change" "unneeded to check change" check ${{ steps.init.outputs.MANIFEST_PATH }} ${{ steps.init.outputs.PKG_REPO_PATH }} ${{ steps.init.outputs.PKG_BUILD_DIR }} | tail -n1)
          if [ "$CHANGE_OUTPUT" == "No package changes found, exiting." ]; then
            echo ::set-output name=changed::0
          else
            echo ::set-output name=changed::1
          fi
      - name: Install AWS CLI
        if: steps.changes.outputs.changed == 1
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install -y python3-pip
          sudo pip install awscli
      - name: Pull from S3
        if: steps.changes.outputs.changed == 1
        run: |
          set -x
          set -e
          rm -Rf ${{ steps.init.outputs.GH_REPO_ROOT }}/generated-repo
          aws s3 sync \
            s3://${{ steps.init.outputs.s3_bucket }} \
            ${{ steps.init.outputs.GH_REPO_ROOT }}/generated-repo \
            --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      - name: Build Setup
        if: steps.changes.outputs.changed == 1
        run: |
          set -x
          set -e
          if [ ! -d "${{ steps.init.outputs.GH_REPO_ROOT }}/generated-repo" ]; then
            mkdir -p "${{ steps.init.outputs.GH_REPO_ROOT }}/generated-repo"
          else
            sudo chown -R $(whoami) ${{ steps.init.outputs.GH_REPO_ROOT }}/generated-repo
          fi
          if [ -d "${{ steps.init.outputs.PKG_REPO_PATH }}" ]; then
            rm -Rf "${{ steps.init.outputs.PKG_REPO_PATH }}"
          fi
          mv ${{ steps.init.outputs.GH_REPO_ROOT }}/generated-repo "${{ steps.init.outputs.PKG_REPO_PATH }}" || true
          ls -l "${{ steps.init.outputs.PKG_REPO_PATH }}"
      - name: Build
        if: steps.changes.outputs.changed == 1
        run: |
          set -x
          set -e
          export DEBEMAIL="regolith.linux@gmail.com"
          export DEBFULLNAME="Regolith Linux"
          export DEBIAN_FRONTEND=noninteractive
          mkdir -p ~/.gnupg/
          printf "${{ secrets.PACKAGE_PRIVATE_KEY }}" | base64 --decode > ~/.gnupg/private.key
          gpg --batch --import ~/.gnupg/private.key
          ${{ steps.init.outputs.GH_REPO_ROOT }}/.github/scripts/main.sh \
            ${{ steps.init.outputs.GH_REPO_ROOT }} \
            ${{ steps.init.outputs.GH_REPO_ROOT }}/.github/scripts/ext-debian.sh \
            "${{ steps.init.outputs.stage }}" \
            "${{ steps.init.outputs.distro }}" \
            "${{ steps.init.outputs.codename }}" \
            "${{ steps.init.outputs.arch }}" \
            "${{ steps.init.outputs.repo_url }}" \
            Default \
            build \
            ${{ steps.init.outputs.MANIFEST_PATH }} \
            ${{ steps.init.outputs.PKG_REPO_PATH }} \
            ${{ steps.init.outputs.PKG_BUILD_DIR }} | tee -a ${{ steps.init.outputs.GH_REPO_ROOT }}/CHANGELOG_${{ steps.init.outputs.target }}.raw.txt
          mv "${{ steps.init.outputs.PKG_REPO_PATH }}" ${{ steps.init.outputs.GH_REPO_ROOT }}/generated-repo
          cat ${{ steps.init.outputs.GH_REPO_ROOT }}/CHANGELOG_${{ steps.init.outputs.target }}.raw.txt | grep ^CHLOG: | cut -d: -f2 > ${{ steps.init.outputs.GH_REPO_ROOT }}/CHANGELOG_${{ steps.init.outputs.target }}.txt
      - name: Push to S3
        if: steps.changes.outputs.changed == 1
        run: |
          set -x
          set -e
          aws s3 sync \
            ${{ steps.init.outputs.GH_REPO_ROOT }}/generated-repo/ \
            s3://${{ steps.init.outputs.s3_bucket }} \
            --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      - uses: actions/upload-artifact@v3
        if: steps.changes.outputs.changed == 1
        with:
          name: CHANGELOG_${{ steps.init.outputs.target }}
          path: ${{ steps.init.outputs.GH_REPO_ROOT }}/CHANGELOG_${{ steps.init.outputs.target }}.txt
  test:
    needs: build
    uses: ./.github/workflows/test-desktop-installable.yml
  generate-release:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v3
      - name: Concat Release Notes
        id: release-setup
        run: |
          set -x
          set -e
          echo ::set-output name=TIMESTAMP::"$(date +%Y%m%d_%H%M%S)"
          FILES=$(find . -name CHANGELOG\*)
          if [ -n "$FILES" ]; then
            cat CHANGELOG_*/CHANGELOG_*.txt >> CHANGELOG.txt
            echo ::set-output name=changed::1
          else
            echo ::set-output name=changed::0
          fi
      - uses: softprops/action-gh-release@v1
        if: steps.release-setup.outputs.changed == 1
        with:
          body_path: CHANGELOG.txt
          name: Package Build ${{ steps.release-setup.outputs.TIMESTAMP }}
          tag_name: pkgbuild-${{ steps.release-setup.outputs.TIMESTAMP }}
