name: .deb -> S3

on:
  push:
    branches: main
    paths:
      - 'stage/**'
      - '.github/**'
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04 #${{ matrix.host-os }}
    strategy:
      matrix:
        host-os: [ubuntu-20.04] # [ubuntu-20.04, [self-hosted, Linux, ARM64]]
        stage: [unstable] # [unstable, testing, release]
        distro-codename: [ubuntu-focal] # [ubuntu-focal, ubuntu-impish, debian-bullseye]
        include:
          - host-os: ubuntu-20.04
            arch: amd64
          #- host-os: [self-hosted, Linux, ARM64]
          #  arch: arm64
          - distro-codename: ubuntu-focal
            distro: ubuntu
            codename: focal
          #- distro-codename: ubuntu-impish
          #  distro: ubuntu
          #  codename: impish
          #- distro-codename: debian-bullseye
          #  distro: debian
          #  codename: bullseye
    steps:
      - uses: actions/checkout@v2
      - name: Set Job Parameters
        id: init
        run: |
          echo ::set-output name=MANIFEST_PATH::"/tmp/manifests"
          echo ::set-output name=PKG_REPO_PATH::"/tmp/repo"
          echo ::set-output name=PKG_BUILD_DIR::"/tmp/packages"
          echo ::set-output name=stage::${{ matrix.stage }}
          echo ::set-output name=distro::${{ matrix.distro }}
          echo ::set-output name=codename::${{ matrix.codename }}
          echo ::set-output name=arch::${{ matrix.arch }}
          echo ::set-output name=target::${{ matrix.stage }}-${{ matrix.distro }}-${{ matrix.codename }}-${{ matrix.arch }}
          echo ::set-output name=s3_bucket::regolith-${{ matrix.stage }}-${{ matrix.distro }}-${{ matrix.codename }}-${{ matrix.arch }}
          echo ::set-output name=repo_url::https://regolith-${{ matrix.stage }}-${{ matrix.distro }}-${{ matrix.codename }}-${{ matrix.arch }}.s3.us-east-2.amazonaws.com
      - name: Pull Manifest
        run: |
          set -x
          manifest_url="https://${{ steps.init.outputs.s3_bucket }}.s3.us-east-2.amazonaws.com/manifest.txt"
          wget -P "${{ steps.init.outputs.PKG_REPO_PATH }}" "$manifest_url" || true
      - name: Check for changes
        id: changes
        run: |
          set -x
          CHANGE_OUTPUT=$(${{ github.workspace }}/.github/scripts/main.sh ${{ github.workspace }} "${{ steps.init.outputs.stage }}" "${{ steps.init.outputs.distro }}" "${{ steps.init.outputs.codename }}" "${{ steps.init.outputs.arch }}" "unneeded to check change" "unneeded to check change" check | tail -n1)
          if [ "$CHANGE_OUTPUT" == "No package changes found, exiting." ]; then
            echo ::set-output name=changed::0
          else
            echo ::set-output name=changed::1
          fi
      - uses: actions/setup-python@v2
        if: steps.changes.outputs.changed == 1
        with:
          python-version: '3.7'
      - name: Install AWS CLI
        if: steps.changes.outputs.changed == 1
        run: |
          python -m pip install --upgrade pip
          pip install awscli
      - name: Pull from S3
        if: steps.changes.outputs.changed == 1
        run: |
          set -x
          aws s3 sync \
            s3://${{ steps.init.outputs.s3_bucket }} \
            ${{ github.workspace }}/generated-repo \
            --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      - name: Build Setup
        if: steps.changes.outputs.changed == 1
        run: |
          set -x
          if [ -d "${{ steps.init.outputs.PKG_REPO_PATH }}" ]; then
            sudo chown -R runner ${{ github.workspace }}/generated-repo
            mv ${{ github.workspace }}/generated-repo/* "${{ steps.init.outputs.PKG_REPO_PATH }}" || true
            ls ${{ steps.init.outputs.PKG_REPO_PATH }}
          else
            mkdir -p "${{ steps.init.outputs.PKG_REPO_PATH }}"
          fi
      - name: Build
        if: steps.changes.outputs.changed == 1
        run: |
          set -x
          export DEBEMAIL="regolith.linux@gmail.com"
          export DEBFULLNAME="Regolith Linux"
          sudo apt update
          sudo apt install -y devscripts reprepro
          mkdir -p ~/.gnupg/
          printf "${{ secrets.PACKAGE_PRIVATE_KEY }}" | base64 --decode > ~/.gnupg/private.key
          gpg --batch --import ~/.gnupg/private.key
          ${{ github.workspace }}/.github/scripts/main.sh \
            ${{ github.workspace }} \
            "${{ steps.init.outputs.stage }}" \
            "${{ steps.init.outputs.distro }}" \
            "${{ steps.init.outputs.codename }}" \
            "${{ steps.init.outputs.arch }}" \
            "${{ steps.init.outputs.repo_url }}" \
            Default \
            build
          mv "${{ steps.init.outputs.PKG_REPO_PATH }}/repo" ${{ github.workspace }}/generated-repo
      - name: Push to S3
        if: steps.changes.outputs.changed == 1
        run: |
          set -x
          aws s3 sync \
            ${{ github.workspace }}/generated-repo \
            s3://${{ steps.init.outputs.s3_bucket }} \
            --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
