name: Build Packages

on:
  push:
    branches: main
    paths:
      - 'stage/**'
      - '.github/**'
  repository_dispatch:
  workflow_dispatch:

jobs:
  find-updates:
    runs-on: ubuntu-20.04
    steps:
      - name: Set Job Parameters
        id: init
        env:
          STAGE: unstable
          DISTRO: ubuntu
          CODENAME: focal
          ARCH: amd64      
        run: |
          echo ::set-output name=stage::${{ env.STAGE }}
          echo ::set-output name=distro::${{ env.DISTRO }}
          echo ::set-output name=codename::${{ env.CODENAME }}
          echo ::set-output name=arch::${{ env.ARCH }}        
      - uses: actions/checkout@v2
      - name: Find Package Updates
        run: |
          $GITHUB_WORKSPACE/.github/scripts/compute-package-changes.sh $GITHUB_WORKSPACE ${{ steps.init.outputs.stage }}  ${{ steps.init.outputs.distro }}  ${{ steps.init.outputs.codename }}  ${{ steps.init.outputs.arch }} /tmp/manifest-build
      - name: Build Packages
        run: |
          export DEBEMAIL="regolith.linux@gmail.com"
          export DEBFULLNAME="Regolith Linux"
          sudo apt update
          sudo apt install -y devscripts reprepro
          mkdir -p ~/.gnupg/
          printf "${{ secrets.PACKAGE_PRIVATE_KEY }}" | base64 --decode > ~/.gnupg/private.key
          gpg --batch --import ~/.gnupg/private.key 
          $GITHUB_WORKSPACE/.github/scripts/build-debian-package.sh ${{ steps.init.outputs.stage }}  ${{ steps.init.outputs.distro }}  ${{ steps.init.outputs.codename }}  ${{ steps.init.outputs.arch }} /tmp/pkgrepo https://myrepo /tmp/package-build BFE717649A5C3D08
      - name: Verify
        run: find /tmp/pkgrepo