name: Sync Netlify

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install AWS CLI
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install -y python3-pip
          sudo pip install awscli
      - name: Cache Repos
        id: cache-repos
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}
          key: cache-repos      
      - name: Pull from S3
        run: |
          for STAGE in unstable testing release
          do
            for distro_codename in ubuntu-focal ubuntu-jammy debian-bullseye
            do
              for ARCH in amd64 arm64
              do
                DISTRO=$(echo $distro_codename | cut -d- -f1)
                CODENAME=$(echo $distro_codename | cut -d- -f2)

                echo $STAGE - $DISTRO - $CODENAME - $ARCH
                aws s3 sync \
                  s3://regolith-$STAGE-$DISTRO-$CODENAME-$ARCH \
                  ${{ github.workspace }}/$STAGE-$DISTRO-$CODENAME-$ARCH \
                  --delete
              done
            done
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      - name: Push to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: ${{ github.workspace }}
          production-deploy: true
          deploy-message: "Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_SECRET_KEY }}
          NETLIFY_SITE_ID: c770f27f-9f9b-4f49-89a3-05b3c8537794
